### ISSUE TITLE
log task id in celery tasks

### ISSUE THREAD

**Issue by leohemsted** [alphagov/notifications-api#1168]
by cleaning up the logs we've lost the context of what specific task run a log line was from - 

inside a task, you can use `self.request.task.id` to get a unique task ID, but i think we need to extend the logging stuff from utils if we want to use this - probably inside the `app/celery/celery.py::NotifyCelery` class.

**Comment by imdadahad** [comment]
Is this still relevant?

**Comment by leohemsted** [comment]
i guess? maybe /shrug
