### ISSUE TITLE
consider push notifications

### ISSUE THREAD

**Issue by derhuerst** [alphagov/notifications-api#2765]
hey!

i just came across this service, and wondered if you have already considered push notifications? they have the realtime-ness of SMS, but within the rate-limits, they're usually free.

**Comment by klssmith** [comment]
Hi, that's a good question. The problem with push notifications is that you can't push notifications without the end user's consent - they either need to download your app or say yes on your website. And traditionally acceptance rates for push notifications are very low.

It's something we may explore in future, but it's not a priority at the moment - we're focussing on scaling up our capacity to send email and SMS for now.

**Comment by derhuerst** [comment]
> Hi, that's a good question. The problem with push notifications is that you can't push notifications without the end user's consent - they either need to download your app or say yes on your website. And traditionally acceptance rates for push notifications are very low.

Yeah, I need to do that. But for essential notifications from e.g. my local government, I'd do that. Also, in order to receive SMS notifications, I need to give my phone number.
