### ISSUE TITLE
Non-ASCII characters in email addresses

### ISSUE THREAD

**Issue by adamlocker** [alphagov/notifications-api#2830]
We use notify with our [Register a Food Business](https://www.gov.uk/food-business-registration) service at the FSA.

We recently had an issue where sending an email using notify failed because the email address for the business contain a vowel with an umlaut.

Could someone advise if this can be fixed or is a problem with our implementation please?

**Comment by quis** [comment]
Hey @adamlocker can you raise a ticket at https://www.notifications.service.gov.uk/support please?

It would help us if you could say which character was the problem (for example ö or ü) and which part of the email address contained the character. So for localpart@domain.tld is the character in the local part, domain or <acronym title="top level domain">tld</acronym>?
