### ISSUE TITLE
Using a list token in an email template

### ISSUE THREAD

**Issue by naeemsarfraz-initialspark** [alphagov/notifications-api#2857]
I'm currently doing work on behalf of CCS and are looking for some feedback personalising an email using a list token.

I have a token in my email template ((errors)) for example. Using the Java client I am supplying an empty list like so: `personalisation.put("errors", Collections.<String> emptyList())`. There are occasions where I don't have content for this token and other information in the email will suffice.

This token is not being replaced and `((errors))` remains in the email. I don't want to send a list of 1 with an empty string as a bullet point will be rendered. Can you advise if the API can handle an empty list?

**Comment by quis** [comment]
Hi @naeemsarfraz-initialspark can you raise a ticket at https://www.notifications.service.gov.uk/support or come talk to us on [our channel on cross-government Slack](https://ukgovernmentdigital.slack.com/messages/C0E1ADVPC)? We don’t formally offer support through Github.

**Comment by naeemsarfraz-initialspark** [comment]
Thanks, but I don't have access to either.

**Comment by naeemsarfraz-initialspark** [comment]
Thanks, but I don't have access to either.

**Comment by quis** [comment]
You don’t need a government email address to raise a ticket [on our support page](https://www.notifications.service.gov.uk/support ). As long as you’re working for a government or other public sector organisation, like CCS, we’ll be happy to answer your question there.
